name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.yarnpkg.com

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Yarn dependencies
        run: yarn install

      - name: Yarn Lint
        run: yarn lint

      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'

      - name: Install pip dependencies
        run: python -m pip install --upgrade pip flake8

      - name: Flake8
        run: flake8 api core
